packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  drizzle-kit: ^0.23.0
  drizzle-orm: ^0.32.0
  eslint: ^8.57.0
  "@fontsource/raleway": ^5.1.1
  jsx-email: ^1.10.11
  pg: ^8.13.1
  prettier: ^3.4.2
  "@sentry/core": ^8.52.1
  "@sentry/nextjs": ^8.52.1
  "@sentry/node": ^8.52.1
  "@sentry/utils": ^8.52.1
  "@spotlightjs/spotlight": ^2.10.3
  superjson: ^2.2.2
  tailwindcss: ^3.4.1
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": ^0.5.16
  "prettier-plugin-tailwindcss": ^0.5.13
  "@tanstack/react-query": ^5.65.1
  "@tanstack/react-query-next-experimental": ^5.65.1
  "@trpc/client": 11.0.0-rc.461
  "@trpc/next": 11.0.0-rc.461
  "@trpc/react-query": 11.0.0-rc.461
  "@trpc/server": 11.0.0-rc.461
  tsx: ^4.19.2
  typescript: ^5.7.3
  "@types/node": ^20.14.9
  "@types/pg": ^8.11.6
  vitest: "~2.1.1"
  "@vitest/coverage-v8": "~2.1.1"
  "vite-tsconfig-paths": "^5.1.4"
  zod: ^3.24.1

  react: ^19
  react-dom: ^19
  "@types/react": ^19
  "@types/react-dom": ^19
